const custom = require("eslint-config-custom")

// src/assets/icons/final is generated by `build:icons` (@svgr/cli).
module.exports = [{ ignores: ["dist/**", "src/assets/icons/final/**"] }, ...custom]
